version: '2'
services:
  zookeeper:
    image: daocloud.io/daocloud/zookeeper:latest
    labels:
      io.daocloud.dce.compose.endpoint-spec.mode: dnsrr
  dubbo-admin:
    image: daocloud.io/daocloud/dubbo-admin:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
  dubbo-provider:
    image: daocloud.io/daocloud/dubbo-provider:latest
    ports:
      - 8081:8080
    depends_on:
      - zookeeper
  dubbo-consumer:
    image: daocloud.io/daocloud/dubbo-consumer:latest
    ports:
      - 8082:8080
    depends_on:
      - zookeeper
